---
title: "Wie wirkt sich Ernährung und Sport auf den BMI aus?"
author: "Nele Hauck, Oliver Lucius"
date: today
format: html
---

# Report von Nele Hauck und Oliver Lucius

## 1. Definition/Formulierung der Fragestellung

::: {.callout-note icon="false"}
## Aufgabenstellung (10 Pkt.)

Definieren Sie eine Sie interessierende bzw. interessante Fragestellung im Zusammenhang mit dem Datensatz:

-   Was interessiert Sie an dem Datensatz?
-   Welche spezifische Fragestellung würden Sie gern mit Hilfe des Datensatzes beantworten?
-   Was erwarten Sie, angesichts Ihrer Fragestellung, bezüglich des Datensatzes?
:::

### Fragestellung: Was sind die treibenden Faktoren für einen gesunden BMI und wie wirkt sich dieser auf Sport- und Ernährungsgewohnheiten aus?

(! BITTE KRITISIEREN BZW. VERBESSERN)

### Was interessiert Sie an dem Datensatz?

-   Zusammenhänge zwischen Lebensstilfaktoren: Ich möchte verstehen, wie stark körperliche Aktivität und Ernährungsverhalten miteinander verbunden sind und ob sie sich gegenseitig beeinflussen.

-   Gesundheitsverhalten im Alltag: Mich interessiert, welche Muster oder Typen von gesundem Verhalten (z. B. „sportlich & gesund ernährend“) sich in der Bevölkerung erkennen lassen.

-   Präventive Bedeutung: Ich möchte herausfinden, welche Verhaltensweisen am stärksten zu einem gesunden BMI beitragen und somit Ansatzpunkte für Gesundheitsförderung liefern.

### Welche Fragestellungen würden Sie gern mit Hilfe des Datensatzes beantworten?

###### Deskriptiv

-   Wie ist die **Verteilung des BMI** in der Stichprobe?

-   Welche **Sportarten** werden am häufigsten betrieben?

-   Wie unterscheiden sich **Kalorienaufnahme und -verbrauch** zwischen Männern und Frauen?

-   Haben sportreibende Personen einen signifikant niedrigeren BMI als Nicht-Sportler?

-   Was ist der Anteil an Sportlern vs. Nicht-Sportler?

-   Wie ist die generelle Ernährungsgewohnheit im Datensatz?

-   Wie ist die Altersverteilung im Datensatz?

###### Analysierend

-   Wie stark beeinflussen sich BMI, Essens- und Sportgewohnheiten gegenseitig?
-   Ist der BMI ein guter Prediktor für Essens- und Sportgewohnheiten?
-   Besteht ein wechselseitiger Zusammenhang zwischen körperlicher Aktivität und gesundem Ernährungsverhalten, und wenn ja, in welche Richtung wirkt dieser Zusammenhang stärker?
-   Wie wirken sich die unterschiedliche Typen von Sport (Krafttraining, Ausdauer, etc.) auf die Ernährungsweise und den BMI aus?
-   Wie viele Features sind notwendig, um den BMI mit 95% Genauigkeit zu bestimmen? (geht vllt. zu sehr Richtung Modelltraining)

###### Geschlechtsspezifische Unterschiede

-   Leben grundsätzlich Frauen oder Männer gesünder? Welches Geschlecht treibt mehr Sport bzw. ernährt sich gesünder?
-   Unterscheidet sich die Art und Weise wie Frauen und Männer Sport treiben? Gibt es geschlechtsspezifische Cluster?

### Text

Ziel des Reports ist es, die Zusammenhänge zwischen Gesundheit, Ernährung und Sport zu untersuchen. Dafür kommt der Datensatz "Life Style Data" von der Online-Plattform Kaggle zum Einsatz. In diesem Datensatz werden von 20000 Personen eine Momentaufnahme der biologischen Merkmale sowie der Ernährungs- und Trainingsgewohnheiten erfasst. Beispielsweise wird die Trainingsart, wie HIIT oder Krafttraining, oder die Kalorien pro Mahlzeit aufgezeichnet. Durch diese detaillierten Informationen lassen sich Faktoren identifizieren, die eine Antwort auf die zentrale Fragestellung des Reports liefern:

**Was sind die treibenden Faktoren für einen gesunden BMI und wie wirkt sich dieser auf Sport- und Ernährungsgewohnheiten aus?**

## 2. Laden der Daten

::: {.callout-note icon="false"}
## Aufgabenstellung (10 Pkt.)

Laden Sie die Daten in die R-Sitzung und verschaffen Sie sich einen ersten Überblick \* Welche Typen sind enthalten? \* Ist sichergestellt, dass alle Daten den richtigen Typ haben? \* Haben die Daten irgendwelche "Seltsamkeiten" mit denen Sie umgehen müssen, wie z.B. anders codierte `NA`'s, mehrere Tabellen, ... etc. \* Je nach Datensatz können Sie die Daten auch in eine Datenbank laden und dann auf diese in R zugreifen.

Beschreiben Sie, was Sie tun müssen, bevor Sie die Daten im nächsten Abschnitt aufbereiten und bearbeiten können!
:::

###### Deskriptiv

-   Wie ist die **Verteilung des BMI** in der Stichprobe?

-   Welche **Sportarten** werden am häufigsten betrieben?

-   Wie unterscheiden sich **Kalorienaufnahme und -verbrauch** zwischen Männern und Frauen?

-   Haben sportreibende Personen einen signifikant niedrigeren BMI als Nicht-Sportler?

-   Was ist der Anteil an Sportlern vs. Nicht-Sportler?

-   Wie ist die generelle Ernährungsgewohnheit im Datensatz?

-   Wie ist die Altersverteilung im Datensatz?

### Text

Der Datensatz umfasst 20000 Zeilen und 54 Features. Von diesen 54 Features sind 40 numerisch, 9 kategorial und die verbleibenden 5 unstrukturiert. Alle Features lassen sich weiter in 4 Bereiche unterteilen:

1. Biologische Daten: Alter, Geschlecht, Gewicht, Größe
2. Gesundheitliche Faktoren: Daten zum Herzschlag, Muskelanteil, Fettanteil, BMI,
3. Ernährung: Trinkmenge, Anzahl der Mahlzeiten pro Tag, (Kalorien, Proteine, Kalorien pro Tag oder pro Mahlzeit?)
4. Training: Trainingsdauer, Trainingsart, Schwierigkeitsgrad, Trainingseinheiten pro Woche, verbrannte Kalorien, Erfahrungslevel

Die genannten Features pro Bereich bilden nur einen Ausschnitt der 54 Features dar. Dennoch hilft dieser zu verstehen, welche Art von Daten im Datensatz vorliegen. 
Insgesamt hat der Datensatz eine hohe Qualität, da keine fehlende Werte existieren. Beispielsweise ist für alle 20000 Zeilen der Wert für den BMI vorhanden. Folglich muss man nicht mit fehlenden Werte umgehen.
Dennoch müssen manche Features aus dem Datensatz entfernt werden. Diese Features enthalten keine sinnvollen Informationen oder es ist unklar, was sie aussagen sollen. So trägt jedes Gericht den Namen "Other", woraus keine Rückschlüsse auf Kalorien, Proteine, etc. geschlossen werden kann. Daher werden solche Features aus dem Datensatz entfernt.



## 3. Bearbeiten/Transformieren der Daten

::: {.callout-note icon="false"}
## Aufgabenstellung (15 Pkt.)

In diesem Abschnitt sollten Sie alle notwendigen Transformationen/Bereiningungen/... etc. der Daten vornehmen (Data Muning, Data Cleansing), wie z.B.: \* Umcodierung von Daten, z.B. numerisch in kategorial \* Subsetting der Daten \* Joining von Datentabellen - falls nötig. Welcher Join ist notwendig? Warum? \* ...

Verschaffen Sie sich eine Übersicht der transformierten Daten. Sie können hierzu Hilfsmittel wie `glimpse()`, `skim()` und `head()` benutzen, um Ihre Erläuterungen zu veranschaulichen.

Sind die sich ergebenden Daten so, wie Sie es erwartet haben? Warum oder warum nicht?
:::

## 4. Geeignete Visualisierung und Aggregation der Daten

::: {.callout-note icon="false"}
## Aufgabenstellung (15 Pkt.)

Fassen Sie die Daten in einer geeigenten Form zur Beantwortung Ihrer formulierten Fragestellung zusammen. Ziehen Sie auch geeignete Visualisierungen der transformierten und/oder aggregierten Daten heran, um Ihre Aussagen entsprechend zu untermauern oder zu veranschaulichen.

Hier könne Sie auch geeignete statistische Verfahren bzw. Modellierungen nutzen, falls diese Ihnen bezüglich Ihrer Fragestellung weiterhelfen.
:::

## 5. Zusammenfassung und Schlussfolgerung

::: {.callout-note icon="false"}
## Aufgabenstellung (10 Pkt.)

Fassen Sie hier Ihre Fragestellung und Ihre Erkenntnisse aus Ihrer Analyse zusammen.

Sind Ihre Erkenntnisse das, was Sie erwartet haben? Warum oder warum nicht?
:::

## Quellenverzeichnis