---
title: "Wie wirkt sich Ernährung und Sport auf den BMI aus?"
author: "Nele Hauck, Oliver Lucius"
date: today
format: html
---

# Report von Nele Hauck und Oliver Lucius

## 1. Definition/Formulierung der Fragestellung

::: {.callout-note icon="false"}
## Aufgabenstellung (10 Pkt.)

Definieren Sie eine Sie interessierende bzw. interessante Fragestellung im Zusammenhang mit dem Datensatz:

-   Was interessiert Sie an dem Datensatz?
-   Welche spezifische Fragestellung würden Sie gern mit Hilfe des Datensatzes beantworten?
-   Was erwarten Sie, angesichts Ihrer Fragestellung, bezüglich des Datensatzes?
:::

### Fragestellung: Was sind die treibenden Faktoren für einen gesunden BMI und wie wirken sich Sport- und Ernährungsgewohnheiten auf diesen aus?

(! BITTE KRITISIEREN BZW. VERBESSERN)

### Was interessiert Sie an dem Datensatz?


### Welche Fragestellungen würden Sie gern mit Hilfe des Datensatzes beantworten?

###### Deskriptiv


###### Analysierend

###### Geschlechtsspezifische Unterschiede


### Text



## 2. Laden der Daten

::: {.callout-note icon="false"}
## Aufgabenstellung (10 Pkt.)

Laden Sie die Daten in die R-Sitzung und verschaffen Sie sich einen ersten Überblick \* Welche Typen sind enthalten? \* Ist sichergestellt, dass alle Daten den richtigen Typ haben? \* Haben die Daten irgendwelche "Seltsamkeiten" mit denen Sie umgehen müssen, wie z.B. anders codierte `NA`'s, mehrere Tabellen, ... etc. \* Je nach Datensatz können Sie die Daten auch in eine Datenbank laden und dann auf diese in R zugreifen.

Beschreiben Sie, was Sie tun müssen, bevor Sie die Daten im nächsten Abschnitt aufbereiten und bearbeiten können!
:::

###### Deskriptiv


### Text



## 3. Bearbeiten/Transformieren der Daten

::: {.callout-note icon="false"}
## Aufgabenstellung (15 Pkt.)

In diesem Abschnitt sollten Sie alle notwendigen Transformationen/Bereiningungen/... etc. der Daten vornehmen (Data Muning, Data Cleansing), wie z.B.: \* Umcodierung von Daten, z.B. numerisch in kategorial \* Subsetting der Daten \* Joining von Datentabellen - falls nötig. Welcher Join ist notwendig? Warum? \* ...

Verschaffen Sie sich eine Übersicht der transformierten Daten. Sie können hierzu Hilfsmittel wie `glimpse()`, `skim()` und `head()` benutzen, um Ihre Erläuterungen zu veranschaulichen.

Sind die sich ergebenden Daten so, wie Sie es erwartet haben? Warum oder warum nicht?
:::

In diesem Abschnitt werden die gegebenen Daten bereinigt und für die weitere Analyse vorbereitet. Dazu gehören die Überprüfung auf fehlende oder fehlerhafte Werte, die Umwandlung von Variabken in geeignete Datentypen, sowie gegebenenfalls das Zusammenführen und Filtern relevanter Daten.

### Überblick über die Rohdaten

### Umkodierungen/Datentypen anpassen

### Bereinigung (NA, fehlerhafte Werte, negative Werte)
### Subsetting (z.B. nur Erwachsene/vollständige Fälle)
### Joins durchführen
### Neue Variablen erstellen

## 4. Geeignete Visualisierung und Aggregation der Daten

::: {.callout-note icon="false"}
## Aufgabenstellung (15 Pkt.)

Fassen Sie die Daten in einer geeigenten Form zur Beantwortung Ihrer formulierten Fragestellung zusammen. Ziehen Sie auch geeignete Visualisierungen der transformierten und/oder aggregierten Daten heran, um Ihre Aussagen entsprechend zu untermauern oder zu veranschaulichen.

Hier könne Sie auch geeignete statistische Verfahren bzw. Modellierungen nutzen, falls diese Ihnen bezüglich Ihrer Fragestellung weiterhelfen.
:::

## 5. Zusammenfassung und Schlussfolgerung

::: {.callout-note icon="false"}
## Aufgabenstellung (10 Pkt.)

Fassen Sie hier Ihre Fragestellung und Ihre Erkenntnisse aus Ihrer Analyse zusammen.

Sind Ihre Erkenntnisse das, was Sie erwartet haben? Warum oder warum nicht?
:::

## Quellenverzeichnis